### PR TITLE
Python3 with application initialization

### PR DESCRIPTION
**Pull request by rbu**
This needs https://github.com/zopefoundation/Zope/pull/277 and https://github.com/zopefoundation/Zope/pull/281 to be merged in Zope

### CODE REVIEW

**Comment by icemac** [comment]
If fails on Python 2.7, but I am not sure why.

**Comment by veritazx** [comment]
Thank you for this! Was wondering where session-init had gone. Didn't think far enough to realize the Application was missing during Product initialization (I just thought I didn't find it when I tried to fix the session initialization).
But got some questions: Should temp_folder/session_data (which is configurable in the session data manager) not better be retrieved from the session data manager during initialize instead of beeing hard-coded here? Is there a way to make sure the sdm is installed before the ZODBMountPoint-initialize happens?

**Comment by rbu** [comment]
The initialization of SessionDataManager in this product has a bad smell, but I don't see a way to handle this differently without a major API change. The order in which products are loaded is deterministic (at least), but it's dependent on the user configuration. As seen in [OFS/Application.py:import_products](https://github.com/zopefoundation/Zope/blob/ba9bee707a310e8cf7d053e540df345baa5ac669/src/OFS/Application.py#L369), the order of products is by Products paths, and then by name within each path.

So by that logic, Products.TemporaryFolder will usually load after Products.Sessions (except when users have TemporaryFolder in a filesystem path that is included before Sessions)

I'll adapt the buildout.cfg so that the build is green and then would like to merge this. ACK?

**Comment by icemac** [comment]
Released to PyPI as https://pypi.org/project/Products.TemporaryFolder/5.1/

**Comment by rbu** [comment]
:champagne: thanks

**Pull request merged**
